Fix log and stdout formatting with correct separators
whittlem/pycryptobot pull request #394
Opened 2021-07-24 08:28 UTC by stevegregev

## Description

When I tried to import the output of the script to a spreadsheet, I noticed that the field separators are inconsistent: some are doubled up, others are missing and still others are missing in certain cases. This minor change will fix the stdout and log output, as well as making the code more consistent in handling the pipe separator in the output.

## Type of change

Please make your selection.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a new dependency
- [ ] Code Maintainability / comments
- [ ] Code Refactoring / future-proofing

## How Has This Been Tested?

Made the change locally and verified the output is as expected in all cases. No functionality changes.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added pytest unit tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2021-07-26 08:46 UTC, markhollingworth-worthit approved these changes

2021-07-26 10:23 UTC, markhollingworth-worthit approved these changes

2021-07-26 14:46 UTC, markhollingworth-worthit submitted a review, later dismissed

2021-07-30 15:30 UTC, hebawom requested changes
I've noticed this too. Good job.

2021-07-30 15:31 UTC, hebawom submitted a review, later dismissed
meant to approve

2021-08-02 10:26 UTC, whittlem commented
Thanks for the update

2021-08-02 10:27 UTC, merged